@host=http://localhost:8080
@baseUrl=/api/v1

PUT {{host}}{{baseUrl}}/users/test
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjowLCJleHAiOjE2OTAzMzUyNjQzNTl9.6YfUygTlzVFC13HSGQGvuqzwLQFwzOgxOzp4rY-Dvy4
Content-Type: application/json

{
    "first_name": "rouzbeh",
    "last_name": "sabzehei",
    "email": "rouzbehsbz@gmail.com",
    "password": ""
}