@host=http://localhost:8080
@baseUrl=/api/v1

POST {{host}}{{baseUrl}}/users
Content-Type: application/json

{
    "firstname": "11212",
    "last_name": "sabzehei",
    "email": "password",
    "password": "password"
}