@host=http://localhost:8080
@baseUrl=/api/v1

PUT {{host}}{{baseUrl}}/users/test
Authorization: asasasasas
Content-Type: application/json

{
    "firstname": "11212",
    "last_name": "sabzehei",
    "email": "password",
    "password": "password"
}